[versions]
springBootVersion = "4.0.0"
openApiPluginVersion = "7.17.0"
springDocOpenApiVersions = "2.8.14"
lombokGradlePluginVersion = "9.1.0"

[libraries]
springDocOpenApiWebfluxUi = { group = "org.springdoc", name = "springdoc-openapi-starter-webflux-ui", version.ref = "springDocOpenApiVersions" }
springDocOpenApiWebfluxApi = { group = "org.springdoc", name = "springdoc-openapi-starter-webflux-api", version.ref = "springDocOpenApiVersions" }

[plugins]
spring-boot-gradle-plugin = { id = "org.springframework.boot", version.ref = "springBootVersion" }
openapi-generator-plugin = { id = "org.openapi.generator", version.ref = "openApiPluginVersion" }
lombok-gradle-plugin = { id = "io.freefair.lombok", version.ref = "lombokGradlePluginVersion" }